
name: 'fueled_events'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dev' # Default is generally `default`.

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  fueled_events:
    # Sources
    fueled__atomic_schema: 'fueled_events' # If not `fueled_atomic`, set to to the schema written by Fueled's warehouse adapter
    landing_page_checkout: 'https://shop.yourwebsite.com/checkouts/'
    landing_page_account: 'https://www.yourwebsite.com/account/'
    direct_channel: 'yourwebsite'
    # Control whether to include S3 destination data
    include_s3_destination_data: true  # Set to false for projects without S3 data
    s3_destination_date: '2025-07-21'
    # Enable/disable specific models
    enable_cart_viewed: true
    enable_checkout_created: false
    enable_logged_in: true
    enable_newsletter_signup_completed: true
    enable_order_completed: true
    enable_pages: true
    enable_product_added: true
    enable_product_list_viewed: true
    enable_product_removed: true
    enable_product_viewed: true
    enable_products_searched: true
    enable_signed_up: true
    enable_user_attribution: true
    session_interval: 60
