
name: 'fueled_events'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dev' # Default is generally `default`.

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  fueled_events:
    # Sources
    fueled__atomic_schema: 'fueled_events' # If not `fueled_atomic`, set to to the schema written by Fueled's warehouse adapter
    landing_page_checkout: 'https://shop.cutsclothing.com/checkouts/'
    landing_page_account: 'https://www.cutsclothing.com/account/'

models:
  fueled_events:
    base:
      scratch:
        +schema: "scratch"
        +tags: "scratch"
        fueled_events_base_order_updated:
          +enabled: false
        fueled_events_base_checkout_updated:
          +enabled: false
        fueled_events_base_users:
          +enabled: false
        fueled_events_base_subscription_created:
          +enabled: false
        fueled_events_base_subscription_cancelled:
          +enabled: false
        fueled_events_base_subscription_activated:
          +enabled: false
        bigquery:
          fueled_events_base_checkout_line_items:
            +enabled: false
    intermediate:
      +schema: "intermediate"
      +materialized: table
    mart:
      +schema: "mart"
      +materialized: table
