{{ config(materialized='ephemeral') }}

{% if var('include_s3_destination_data', false) %}
SELECT
    JSON_VALUE(context, '$.os.name')                                                     AS context_os_name,
    COALESCE(anonymousId, JSON_VALUE(context, '$.anonymousId'))                          AS context_anonymous_id,
    JSON_VALUE(context, '$.campaign.gclid')                                              AS context_campaign_gclid,
    JSON_VALUE(context, '$.version')                                                     AS context_version,
    JSON_VALUE(context, '$.fb.fbc')                                                      AS context_fb_fbc,
    TIMESTAMP_SECONDS(original_timestamp)                                                AS timestamp,
    CAST(NULL          AS STRING)                                                        AS context_destination_id,
    JSON_VALUE(context, '$.campaign.klaviyoId')                                          AS context_campaign_klaviyo_id,
    'server'                                                                           AS channel,
    JSON_VALUE(context, '$.page.referrer')                                              AS context_page_referrer,
    JSON_VALUE(context, '$.campaign.medium')                                             AS context_campaign_medium,
    TIMESTAMP_SECONDS(original_timestamp)                                                AS sent_at,
    JSON_VALUE(context, '$.fueledExternalId')                                           AS context_fueled_external_id,
    CAST(JSON_VALUE(properties, '$.height')  AS INT64)                                   AS height,
    TIMESTAMP_SECONDS(hydration_timestamp)                                               AS loaded_at,
    JSON_VALUE(context, '$.page.path')                                                  AS context_page_path,
    JSON_VALUE(context, '$.page.url')                                                   AS context_page_url,
    JSON_VALUE(context, '$.klaviyoExchangeId')                                           AS context_klaviyo_exchange_id,
    JSON_VALUE(context, '$.page.path')                                                                               AS path,
    JSON_VALUE(context, '$.ga4.clientId')                                               AS context_ga4_client_id,
    event_id                                                                           AS id,
    CAST(JSON_VALUE(context, '$.debug') AS BOOL)                                       AS context_debug,
    JSON_VALUE(context, '$.referrer')                                                  AS context_referrer,
    JSON_VALUE(context, '$.ga4.userId')                                                AS context_ga4_user_id,
    event_name                                                                         AS name,
    JSON_VALUE(properties, '$.search')                                                  AS search,
    JSON_VALUE(context, '$.page.title')                                                AS context_page_title,
    TIMESTAMP_SECONDS(hydration_timestamp)                                              AS received_at,
    COALESCE(
                JSON_VALUE(properties, '$.phone'),
                JSON_VALUE(customer,   '$.phone'),
                JSON_VALUE(context,    '$.traits.phone')
                )                                                                              AS context_traits_phone,
    JSON_VALUE(context, '$.ip')                                                       AS context_request_ip,
    CAST(JSON_VALUE(context, '$.initialized') AS BOOL)                                 AS context_initialized,
    CAST(JSON_VALUE(properties, '$.height')  AS INT64)                                  AS context_page_height,
    COALESCE(sessionId, JSON_VALUE(context, '$.sessionId'))                            AS context_session_id,
    CAST(NULL          AS STRING)                                                      AS context_destination_type,
    JSON_VALUE(context, '$.library.version')                                           AS context_library_version,
    JSON_VALUE(context, '$.campaign.content')                                          AS context_campaign_content,
    JSON_VALUE(properties, '$.url')                                                     AS url,
    JSON_VALUE(context, '$.campaign.name')                                             AS context_campaign_name,
    CAST(JSON_VALUE(properties, '$.width')   AS INT64)                                  AS width,
    JSON_VALUE(context, '$.fb.externalId')                                              AS context_fb_external_id,
    JSON_VALUE(context, '$.ga4.sessionId')                                              AS context_ga4_session_id,
    sourceEndpointId                                                                  AS context_source_id,
    CAST(JSON_VALUE(properties, '$.width')   AS INT64)                                  AS context_page_width,
    JSON_VALUE(context, '$.campaign.id')                                               AS context_campaign_id,
    JSON_VALUE(context, '$.campaign.source')                                           AS context_campaign_source,
    CAST(JSON_VALUE(context, '$.campaign.term')  AS BOOL)                               AS context_campaign_term,
    JSON_VALUE(context, '$.library.name')                                              AS context_library_name,
    JSON_VALUE(properties, '$.referrer')                                                AS referrer,
    CAST(NULL          AS STRING)                                                      AS context_source_type,
    JSON_VALUE(context, '$.timezone')                                                  AS context_timezone,
    userId                                                                             AS user_id,
    JSON_VALUE(context, '$.fb.fbp')                                                     AS context_fb_fbp,
    JSON_VALUE(context, '$.fb.eventId')                                                AS context_fb_event_id,
    CAST(NULL          AS STRING)                                                      AS context_ip,
    JSON_VALUE(context, '$.userAgent')                                                 AS context_user_agent,
    schema_version                                                                    AS context_endpoint_version,
    TIMESTAMP_SECONDS(original_timestamp)                                               AS uuid_ts,
    CAST(JSON_VALUE(context, '$.offline')  AS BOOL)                                    AS context_offline,
    JSON_VALUE(properties, '$.search')                                                 AS context_page_search,
    JSON_VALUE(context, '$.traits.address.countryCode')                                AS context_traits_address_country_code,
    JSON_VALUE(properties, '$.title')                                                  AS title,
    JSON_VALUE(context, '$.app')                                                       AS context_app,
    JSON_VALUE(context, '$.locale')                                                    AS context_locale,
    COALESCE(
                JSON_VALUE(properties, '$.email'),
                JSON_VALUE(customer,   '$.email'),
                JSON_VALUE(context,    '$.traits.email')
                )                                                                              AS context_traits_email,
    TIMESTAMP_SECONDS(original_timestamp)                                               AS original_timestamp,
    JSON_VALUE(context, '$.traits.name')                                               AS context_traits_name,
    CAST(JSON_VALUE(context, '$.traits.lifetimeValue') AS FLOAT64)                     AS context_traits_lifetime_value,
    JSON_VALUE(context, '$.traits.address.stateCode')                                  AS context_traits_address_state_code,
    JSON_VALUE(context, '$.traits.visitorType')                                        AS context_traits_visitor_type,
    COALESCE(
                JSON_VALUE(context, '$.traits.externalCustomerId'),
                JSON_VALUE(customer,   '$.externalCustomerId')
                )                                                                              AS context_traits_external_customer_id,
    JSON_VALUE(context, '$.page.hash')                                                 AS context_page_hash,
    JSON_VALUE(context, '$.traits.shopifyCustomerId')                                  AS context_traits_shopify_customer_id,
    JSON_VALUE(context, '$.traits.address.postalCode')                                 AS context_traits_address_postal_code,
    JSON_VALUE(context, '$.traits.address.city')                                       AS context_traits_address_city,
    CAST(NULL          AS STRING)                                                      AS _hash,
    COALESCE(
                JSON_VALUE(properties, '$.first_name'),
                JSON_VALUE(customer,   '$.firstName'),
                JSON_VALUE(context,    '$.traits.firstName')
                )                                                                              AS context_traits_first_name,
    JSON_VALUE(context, '$.traits.address.street')                                     AS context_traits_address_street,
    CAST(JSON_VALUE(context, '$.traits.orderCount')  AS INT64)                         AS context_traits_order_count,
    JSON_VALUE(context, '$.traits.address.state')                                      AS context_traits_address_state,
    JSON_VALUE(context, '$.traits.address.country')                                    AS context_traits_address_country,
    COALESCE(
                JSON_VALUE(properties, '$.last_name'),
                JSON_VALUE(customer,   '$.lastName'),
                JSON_VALUE(context,    '$.traits.lastName')
                )                                                                              AS context_traits_last_name,
    CAST(NULL          AS STRING)                                                      AS context_campaign_source_platform,
    CAST(NULL          AS STRING)                                                      AS context_campaign_redirect,
    JSON_VALUE(context, '$.campaign.agid')                           AS context_campaign_agid,
    JSON_VALUE(context, '$.campaign.audience')                                         AS context_campaign_audience,
    JSON_VALUE(context, '$.campaign.marketingAudience')                                AS context_campaign_marketing_audience,
    JSON_VALUE(context, '$.campaign.marketingTactic')                                  AS context_campaign_marketing_tactic,
    JSON_VALUE(context, '$.campaign.customerType')                                     AS context_campaign_customertype,
    CAST(JSON_VALUE(context, '$.trackingConsent.analytics') AS BOOL)                   AS context_tracking_consent_analytics,
    CAST(JSON_VALUE(context, '$.trackingConsent.preferences') AS BOOL)                 AS context_tracking_consent_preferences,
    CAST(JSON_VALUE(context, '$.trackingConsent.saleOfData') AS BOOL)                  AS context_tracking_consent_sale_of_data,
    CAST(JSON_VALUE(context, '$.trackingConsent.marketing') AS BOOL)                   AS context_tracking_consent_marketing,
    CAST(NULL          AS STRING)                                                      AS context_campaign_targeting,
    CAST(NULL          AS STRING)                                                      AS context_campaign_fbaudience,
    CAST(NULL          AS STRING)                                                      AS context_campaign_segm,
    CAST(NULL          AS STRING)                                                      AS context_traits_fired_from,
    CAST(NULL          AS STRING)                                                      AS context_traits_custom_client_id,
    CAST(JSON_VALUE(context, '$.traits.ecommerceEvent')   AS BOOL)                      AS context_traits_ecommerce_event,
    CAST(NULL          AS STRING)                                                      AS context_campaign_audiance,
    CAST(JSON_VALUE(context, '$.campaign.medi')      AS BOOL)                            AS context_campaign_medi,
    JSON_VALUE(context, '$.campaign.customer')                                            AS context_campaign_customer,
    JSON_VALUE(context, '$.ipv4')                                                         AS context_ipv4,
    JSON_VALUE(context, '$.ipv6')                                                         AS context_ipv6,
    CAST(JSON_VALUE(context, '$.campaign.campai')   AS BOOL)                              AS context_campaign_campai,
    CAST(NULL          AS BOOL)                                                        AS context_category_preferences_advertising,
    CAST(NULL          AS BOOL)                                                        AS context_category_preferences_data_sharing,
    CAST(NULL          AS BOOL)                                                        AS context_category_preferences_functional,
    CAST(NULL          AS BOOL)                                                        AS context_category_preferences_analytics,
    JSON_VALUE(context, '$.opensendPersistentId')                                      AS context_opensend_persistent_id,
    JSON_VALUE(context, '$.opensendIdToken')                                           AS context_opensend_id_token,
    CAST(JSON_VALUE(context, '$.campaign.campaign_session_abandonment_non_purchaser_w_neiax') AS BOOL) AS context_campaign_campaign_session_abandonment_non_purchaser_w_neiax,
    CAST(JSON_VALUE(context, '$.campaign.mediumEmail')   AS BOOL)                         AS context_campaign_mediumemail,
    CAST(JSON_VALUE(context, '$.campaign.klaviyoId01_j56_je0_asvp5_g4_p9_bs31_vaj1_m') AS BOOL) AS context_campaign_klaviyo_id01_j56_je0_asvp5_g4_p9_bs31_vaj1_m,
    CAST(JSON_VALUE(context, '$.campaign.source_klaviyo')  AS BOOL)                      AS context_campaign_source_klaviyo

FROM {{ source('s3_destination_fueled_events','fueled_events') }}
WHERE event_name = 'Page View'

{% else %}

SELECT
    CAST(NULL AS STRING) AS context_os_name,
    CAST(NULL AS STRING) AS context_anonymous_id,
    CAST(NULL AS STRING) AS context_campaign_gclid,
    CAST(NULL AS STRING) AS context_version,
    CAST(NULL AS STRING) AS context_fb_fbc,
    CAST(NULL AS TIMESTAMP) AS timestamp,
    CAST(NULL AS STRING) AS context_destination_id,
    CAST(NULL AS STRING) AS context_campaign_klaviyo_id,
    CAST(NULL AS STRING) AS channel,
    CAST(NULL AS STRING) AS context_page_referrer,
    CAST(NULL AS STRING) AS context_campaign_medium,
    CAST(NULL AS TIMESTAMP) AS sent_at,
    CAST(NULL AS STRING) AS context_fueled_external_id,
    CAST(NULL AS INT64) AS height,
    CAST(NULL AS TIMESTAMP) AS loaded_at,
    CAST(NULL AS STRING) AS context_page_path,
    CAST(NULL AS STRING) AS context_page_url,
    CAST(NULL AS STRING) AS context_klaviyo_exchange_id,
    CAST(NULL AS STRING) AS path,
    CAST(NULL AS STRING) AS context_ga4_client_id,
    CAST(NULL AS STRING) AS id,
    CAST(NULL AS BOOL) AS context_debug,
    CAST(NULL AS STRING) AS context_referrer,
    CAST(NULL AS STRING) AS context_ga4_user_id,
    CAST(NULL AS STRING) AS name,
    CAST(NULL AS STRING) AS search,
    CAST(NULL AS STRING) AS context_page_title,
    CAST(NULL AS TIMESTAMP) AS received_at,
    CAST(NULL AS STRING) AS context_traits_phone,
    CAST(NULL AS STRING) AS context_request_ip,
    CAST(NULL AS BOOL) AS context_initialized,
    CAST(NULL AS INT64) AS context_page_height,
    CAST(NULL AS STRING) AS context_session_id,
    CAST(NULL AS STRING) AS context_destination_type,
    CAST(NULL AS STRING) AS context_library_version,
    CAST(NULL AS STRING) AS context_campaign_content,
    CAST(NULL AS STRING) AS url,
    CAST(NULL AS STRING) AS context_campaign_name,
    CAST(NULL AS INT64) AS width,
    CAST(NULL AS STRING) AS context_fb_external_id,
    CAST(NULL AS STRING) AS context_ga4_session_id,
    CAST(NULL AS STRING) AS context_source_id,
    CAST(NULL AS INT64) AS context_page_width,
    CAST(NULL AS STRING) AS context_campaign_id,
    CAST(NULL AS STRING) AS context_campaign_source,
    CAST(NULL AS BOOL) AS context_campaign_term,
    CAST(NULL AS STRING) AS context_library_name,
    CAST(NULL AS STRING) AS referrer,
    CAST(NULL AS STRING) AS context_source_type,
    CAST(NULL AS STRING) AS context_timezone,
    CAST(NULL AS STRING) AS user_id,
    CAST(NULL AS STRING) AS context_fb_fbp,
    CAST(NULL AS STRING) AS context_fb_event_id,
    CAST(NULL AS STRING) AS context_ip,
    CAST(NULL AS STRING) AS context_user_agent,
    CAST(NULL AS STRING) AS context_endpoint_version,
    CAST(NULL AS TIMESTAMP) AS uuid_ts,
    CAST(NULL AS BOOL) AS context_offline,
    CAST(NULL AS STRING) AS context_page_search,
    CAST(NULL AS STRING) AS context_traits_address_country_code,
    CAST(NULL AS STRING) AS title,
    CAST(NULL AS STRING) AS context_app,
    CAST(NULL AS STRING) AS context_locale,
    CAST(NULL AS STRING) AS context_traits_email,
    CAST(NULL AS TIMESTAMP) AS original_timestamp,
    CAST(NULL AS STRING) AS context_traits_name,
    CAST(NULL AS FLOAT64) AS context_traits_lifetime_value,
    CAST(NULL AS STRING) AS context_traits_address_state_code,
    CAST(NULL AS STRING) AS context_traits_visitor_type,
    CAST(NULL AS STRING) AS context_traits_external_customer_id,
    CAST(NULL AS STRING) AS context_page_hash,
    CAST(NULL AS STRING) AS context_traits_shopify_customer_id,
    CAST(NULL AS STRING) AS context_traits_address_postal_code,
    CAST(NULL AS STRING) AS context_traits_address_city,
    CAST(NULL AS STRING) AS _hash,
    CAST(NULL AS STRING) AS context_traits_first_name,
    CAST(NULL AS STRING) AS context_traits_address_street,
    CAST(NULL AS INT64) AS context_traits_order_count,
    CAST(NULL AS STRING) AS context_traits_address_state,
    CAST(NULL AS STRING) AS context_traits_address_country,
    CAST(NULL AS STRING) AS context_traits_last_name,
    CAST(NULL AS STRING) AS context_campaign_source_platform,
    CAST(NULL AS STRING) AS context_campaign_redirect,
    CAST(NULL AS STRING) AS context_campaign_agid,
    CAST(NULL AS STRING) AS context_campaign_audience,
    CAST(NULL AS STRING) AS context_campaign_marketing_audience,
    CAST(NULL AS STRING) AS context_campaign_marketing_tactic,
    CAST(NULL AS STRING) AS context_campaign_customertype,
    CAST(NULL AS BOOL) AS context_tracking_consent_analytics,
    CAST(NULL AS BOOL) AS context_tracking_consent_preferences,
    CAST(NULL AS BOOL) AS context_tracking_consent_sale_of_data,
    CAST(NULL AS BOOL) AS context_tracking_consent_marketing,
    CAST(NULL AS STRING) AS context_campaign_targeting,
    CAST(NULL AS STRING) AS context_campaign_fbaudience,
    CAST(NULL AS STRING) AS context_campaign_segm,
    CAST(NULL AS STRING) AS context_traits_fired_from,
    CAST(NULL AS STRING) AS context_traits_custom_client_id,
    CAST(NULL AS BOOL) AS context_traits_ecommerce_event,
    CAST(NULL AS STRING) AS context_campaign_audiance,
    CAST(NULL AS BOOL) AS context_campaign_medi,
    CAST(NULL AS STRING) AS context_campaign_customer,
    CAST(NULL AS STRING) AS context_ipv4,
    CAST(NULL AS STRING) AS context_ipv6,
    CAST(NULL AS BOOL) AS context_campaign_campai,
    CAST(NULL AS BOOL) AS context_category_preferences_advertising,
    CAST(NULL AS BOOL) AS context_category_preferences_data_sharing,
    CAST(NULL AS BOOL) AS context_category_preferences_functional,
    CAST(NULL AS BOOL) AS context_category_preferences_analytics,
    CAST(NULL AS STRING) AS context_opensend_persistent_id,
    CAST(NULL AS STRING) AS context_opensend_id_token,
    CAST(NULL AS BOOL) AS context_campaign_campaign_session_abandonment_non_purchaser_w_neiax,
    CAST(NULL AS BOOL) AS context_campaign_mediumemail,
    CAST(NULL AS BOOL) AS context_campaign_klaviyo_id01_j56_je0_asvp5_g4_p9_bs31_vaj1_m,
    CAST(NULL AS BOOL) AS context_campaign_source_klaviyo
FROM (SELECT 1) AS dummy
WHERE FALSE

{% endif %}
