{{ config(
    materialized='ephemeral'
) }}

SELECT
  TIMESTAMP_SECONDS(hydration_timestamp) AS received_at,
  JSON_VALUE(properties, '$.billingAddress.city') AS billing_address_city,
  CAST(JSON_VALUE(properties, '$.subtotal') AS FLOAT64) AS subtotal,
  JSON_VALUE(context, '$.ga4.sessionId') AS context_ga4_session_id,
  JSON_EXTRACT(properties, '$.products') AS products,
  JSON_VALUE(context, '$.fueledExternalId') AS context_fueled_external_id,
  JSON_VALUE(properties, '$.id') AS id,
  JSON_VALUE(properties, '$.billingAddress.firstName') AS billing_address_first_name,
  JSON_VALUE(properties, '$.billingAddress.postalCode') AS billing_address_postal_code,
  'S3' AS context_source_type,
  JSON_VALUE(properties, '$.billingAddress.phone') AS billing_address_phone,
  JSON_VALUE(properties, '$.status') AS status,
  'Order Completed' AS event_text,
  JSON_VALUE(properties, '$.id') AS order_id,
  JSON_VALUE(context, '$.ga4.userId') AS context_ga4_user_id,
  JSON_VALUE(properties, '$.cartId') AS cart_id,
  JSON_VALUE(context, '$.ip') AS context_ip,
  CAST(JSON_VALUE(properties, '$.total') AS FLOAT64) AS revenue,
  JSON_VALUE(context, '$.countryCode') AS context_country_code,
  JSON_VALUE(properties, '$.billingAddress.stateCode') AS billing_address_state_code,
  JSON_VALUE(context, '$.userAgent') AS context_user_agent,
  JSON_VALUE(properties, '$.billingAddress.countryCode') AS billing_address_country_code,
  CAST(JSON_VALUE(properties, '$.shipping') AS FLOAT64) AS shipping,
  JSON_VALUE(context, '$.locale') AS context_locale,
  JSON_VALUE(properties, '$.billingAddress.country') AS billing_address_country,
  JSON_VALUE(context, '$.ip') AS context_passed_ip,
  CAST(JSON_VALUE(properties, '$.tax') AS FLOAT64) AS tax,
  CAST(JSON_VALUE(properties, '$.total') AS FLOAT64) AS value,
  TIMESTAMP_SECONDS(original_timestamp) as original_timestamp,
  JSON_VALUE(context, '$.sourceId') AS context_source_id,
  JSON_VALUE(context, '$.fb.fbc') AS context_fb_fbc,
  TIMESTAMP_SECONDS(hydration_timestamp) AS sent_at,
  JSON_VALUE(properties, '$.coupon') AS coupon,
  JSON_VALUE(context, '$.anonymousId') AS context_anonymous_id,
  JSON_VALUE(context, '$.ga4.clientId') AS context_ga4_client_id,
  JSON_VALUE(properties, '$.currency') AS currency,
  timestamp AS loaded_at,
  JSON_VALUE(properties, '$.billingAddress.address') AS billing_address_address,
  TIMESTAMP_SECONDS(original_timestamp) as timestamp,
  affiliation,
  JSON_VALUE(context, '$.userId') AS context_user_id,
  JSON_VALUE(properties, '$.type') AS type,
  JSON_VALUE(context, '$.ip') AS context_request_ip,
  timestamp AS uuid_ts,
  JSON_VALUE(properties, '$.channel') AS channel,
  JSON_VALUE(context, '$.url') AS context_url,
  CAST(NULL AS STRING) AS context_library_name,
  CAST(JSON_VALUE(properties, '$.total') AS FLOAT64) AS total,
  JSON_VALUE(properties, '$.payment_type') AS payment_type,
  'BQ' AS context_destination_type,
  JSON_VALUE(properties, '$.billingAddress.state') AS billing_address_state,
  CAST(NULL AS STRING) AS context_destination_id,
  CAST(JSON_VALUE(properties, '$.discount') AS FLOAT64) AS discount,
  CAST(NULL AS STRING) AS context_library_version,
  CAST(NULL AS STRING) AS context_rudderstack_source,
  JSON_VALUE(context, '$.fb.externalId') AS context_fb_external_id,
  userId AS user_id,
  sourceEndpointId AS context_endpoint_version,
  JSON_VALUE(properties, '$.billingAddress.lastName') AS billing_address_last_name,
  event_name AS event,
  source AS context_source,
  JSON_VALUE(context, '$.fb.fbp') AS context_fb_fbp,
  TRUE AS context_tracking_consent,
  JSON_VALUE(properties, '$.billingAddress.company') AS billing_address_company,
  JSON_VALUE(context, '$.klaviyoExchangeId') AS context_klaviyo_exchange_id,
  JSON_VALUE(context, '$.referrer') AS context_referrer,
  JSON_VALUE(context, '$.campaign.term') AS context_campaign_term,
  JSON_VALUE(context, '$.campaign.id') AS context_campaign_id,
  JSON_VALUE(context, '$.campaign.source') AS context_campaign_source,
  JSON_VALUE(context, '$.campaign.content') AS context_campaign_content,
  JSON_VALUE(context, '$.ga4.sessionId') AS context_session_id,
  CAST(NULL AS BOOL) AS context_offline,
  JSON_VALUE(context, '$.timezone') AS context_timezone,
  JSON_VALUE(context, '$.app') AS context_app,
  JSON_VALUE(context, '$.campaign.medium') AS context_campaign_medium,
  JSON_VALUE(context, '$.campaign.klaviyoId') AS context_campaign_klaviyo_id,
  CAST(NULL AS BOOL) AS context_initialized,
  JSON_VALUE(context, '$.os.name') AS context_os_name,
  CAST(NULL AS BOOL) AS context_debug,
  JSON_VALUE(context, '$.campaign.name') AS context_campaign_name,
  JSON_VALUE(context, '$.version') AS context_version,
  CAST(JSON_VALUE(context, '$.trackingConsent.analytics') AS BOOL) AS context_tracking_consent_analytics,
  CAST(JSON_VALUE(context, '$.trackingConsent.marketing') AS BOOL) AS context_tracking_consent_marketing,
  CAST(JSON_VALUE(context, '$.trackingConsent.saleOfData') AS BOOL) AS context_tracking_consent_sale_of_data,
  CAST(JSON_VALUE(context, '$.trackingConsent.preferences') AS BOOL) AS context_tracking_consent_preferences,
  CAST(NULL AS BOOL) AS context_category_preferences_analytics,
  CAST(NULL AS BOOL) AS context_category_preferences_functional,
  CAST(NULL AS BOOL) AS context_category_preferences_advertising,
  CAST(NULL AS BOOL) AS context_category_preferences_data_sharing
FROM {{ source("s3_destination_fueled_events", "fueled_events") }}
WHERE event_name = 'Order Completed'