{{ config(
    materialized='ephemeral'
) }}

{% if var('include_s3_destination_data', false) %}

SELECT
  -- Select only the columns needed for fueled_events_bronze_order_completed.sql
  affiliation,
  JSON_VALUE(properties, '$.billingAddress.address') AS billing_address_address,
  JSON_VALUE(properties, '$.billingAddress.city') AS billing_address_city,
  JSON_VALUE(properties, '$.billingAddress.company') AS billing_address_company,
  JSON_VALUE(properties, '$.billingAddress.country') AS billing_address_country,
  JSON_VALUE(properties, '$.billingAddress.firstName') AS billing_address_first_name,
  JSON_VALUE(properties, '$.billingAddress.lastName') AS billing_address_last_name,
  JSON_VALUE(properties, '$.billingAddress.phone') AS billing_address_phone,
  JSON_VALUE(properties, '$.billingAddress.postalCode') AS billing_address_postal_code,
  JSON_VALUE(properties, '$.billingAddress.state') AS billing_address_state,
  JSON_VALUE(properties, '$.cartId') AS cart_id,
  JSON_VALUE(properties, '$.coupon') AS coupon,
  JSON_VALUE(properties, '$.currency') AS currency,
  SAFE_CAST(JSON_VALUE(properties, '$.discount') AS FLOAT64) AS discount,
  'Order Completed' AS event_text,
  JSON_VALUE(properties, '$.id') AS order_id,
  JSON_VALUE(properties, '$.payment_type') AS payment_type,
  JSON_EXTRACT(properties, '$.products') AS products,
  SAFE_CAST(JSON_VALUE(properties, '$.total') AS FLOAT64) AS revenue,
  SAFE_CAST(JSON_VALUE(properties, '$.shipping') AS FLOAT64) AS shipping,
  JSON_VALUE(properties, '$.status') AS status,
  SAFE_CAST(JSON_VALUE(properties, '$.subtotal') AS FLOAT64) AS subtotal,
  SAFE_CAST(JSON_VALUE(properties, '$.tax') AS FLOAT64) AS tax,
  SAFE_CAST(JSON_VALUE(properties, '$.total') AS FLOAT64) AS total,
  JSON_VALUE(properties, '$.type') AS type,
  SAFE_CAST(JSON_VALUE(properties, '$.total') AS FLOAT64) AS value,
  COALESCE(JSON_VALUE(context, '$.fueledExternalId'), JSON_VALUE(context, '$.anonymousId')) AS anonymous_id,
  userId AS user_id,
  TIMESTAMP_SECONDS(original_timestamp) as original_timestamp,
  -- Include all context_* columns that would come from the get_shared_event_attributes macro
  JSON_VALUE(context, '$.anonymousId') AS context_anonymous_id,
  JSON_VALUE(context, '$.campaign.content') AS context_campaign_content,
  JSON_VALUE(context, '$.campaign.id') AS context_campaign_id,
  JSON_VALUE(context, '$.campaign.klaviyoId') AS context_campaign_klaviyo_id,
  JSON_VALUE(context, '$.campaign.medium') AS context_campaign_medium,
  JSON_VALUE(context, '$.campaign.name') AS context_campaign_name,
  JSON_VALUE(context, '$.campaign.source') AS context_campaign_source,
  JSON_VALUE(context, '$.campaign.term') AS context_campaign_term,
  JSON_VALUE(context, '$.countryCode') AS context_country_code,
  JSON_VALUE(context, '$.fb.externalId') AS context_fb_external_id,
  JSON_VALUE(context, '$.fb.fbc') AS context_fb_fbc,
  JSON_VALUE(context, '$.fb.fbp') AS context_fb_fbp,
  JSON_VALUE(context, '$.fueledExternalId') AS context_fueled_external_id,
  JSON_VALUE(context, '$.ga4.clientId') AS context_ga4_client_id,
  JSON_VALUE(context, '$.ga4.sessionId') AS context_ga4_session_id,
  JSON_VALUE(context, '$.ga4.userId') AS context_ga4_user_id,
  JSON_VALUE(context, '$.ga4.clientId') AS context_ga_4_client_id,
  JSON_VALUE(context, '$.ga4.sessionId') AS context_ga_4_session_id,
  JSON_VALUE(context, '$.ga4.userId') AS context_ga_4_user_id,
  JSON_VALUE(context, '$.ip') AS context_ip,
  JSON_VALUE(context, '$.klaviyoExchangeId') AS context_klaviyo_exchange_id,
  JSON_VALUE(context, '$.locale') AS context_locale,
  JSON_VALUE(context, '$.os.name') AS context_os_name,
  JSON_VALUE(context, '$.referrer') AS context_referrer,
  JSON_VALUE(context, '$.sourceId') AS context_source_id,
  'S3' AS context_source_type,
  TRUE AS context_tracking_consent,
  SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.analytics') AS BOOL) AS context_tracking_consent_analytics,
  SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.marketing') AS BOOL) AS context_tracking_consent_marketing,
  SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.preferences') AS BOOL) AS context_tracking_consent_preferences,
  SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.saleOfData') AS BOOL) AS context_tracking_consent_sale_of_data,
  JSON_VALUE(context, '$.timezone') AS context_timezone,
  JSON_VALUE(context, '$.url') AS context_url,
  JSON_VALUE(context, '$.userAgent') AS context_user_agent,
  JSON_VALUE(context, '$.userId') AS context_user_id,
  JSON_VALUE(context, '$.version') AS context_version,
  JSON_VALUE(context, '$.library.version') AS context_library_version,
  JSON_VALUE(context, '$.library.name') AS context_library_name,
  sourceEndpointId AS context_endpoint_version,
  JSON_VALUE(context, '$.ip') AS context_passed_ip,
  source AS context_source,
  SAFE_CAST(JSON_VALUE(context, '$.debug') AS BOOL) AS context_debug,
  JSON_VALUE(context, '$.app') AS context_app,
  JSON_VALUE(context, '$.request.ip') AS context_request_ip,
  JSON_VALUE(context, '$.ga4.sessionId') AS context_session_id,
  'BQ' AS context_destination_type,
  SAFE_CAST(NULL AS STRING) AS context_destination_id,
  SAFE_CAST(NULL AS STRING) AS context_rudderstack_source,
  SAFE_CAST(NULL AS BOOL) AS context_offline,
  SAFE_CAST(NULL AS BOOL) AS context_initialized,
  SAFE_CAST(JSON_VALUE(context, '$.categoryPreferences.functional') AS BOOL) AS context_category_preferences_functional,
  SAFE_CAST(JSON_VALUE(context, '$.categoryPreferences.dataSharing') AS BOOL) AS context_category_preferences_data_sharing,
  SAFE_CAST(JSON_VALUE(context, '$.categoryPreferences.analytics') AS BOOL) AS context_category_preferences_analytics,
  SAFE_CAST(JSON_VALUE(context, '$.categoryPreferences.advertising') AS BOOL) AS context_category_preferences_advertising,
  -- Add event_id as the last column (matching fueled_events_bronze_order_completed.sql)
  JSON_VALUE(properties, '$.id') AS event_id
FROM {{ source("s3_destination_fueled_events", "fueled_events") }}
WHERE event_name = 'Order Completed'

{% else %}

-- Return an empty result set with matching column structure when S3 data is disabled
SELECT
  -- Match the columns from the main query
  SAFE_CAST(NULL AS STRING) AS affiliation,
  SAFE_CAST(NULL AS STRING) AS billing_address_address,
  SAFE_CAST(NULL AS STRING) AS billing_address_city,
  SAFE_CAST(NULL AS STRING) AS billing_address_company,
  SAFE_CAST(NULL AS STRING) AS billing_address_country,
  SAFE_CAST(NULL AS STRING) AS billing_address_first_name,
  SAFE_CAST(NULL AS STRING) AS billing_address_last_name,
  SAFE_CAST(NULL AS STRING) AS billing_address_phone,
  SAFE_CAST(NULL AS STRING) AS billing_address_postal_code,
  SAFE_CAST(NULL AS STRING) AS billing_address_state,
  SAFE_CAST(NULL AS STRING) AS cart_id,
  SAFE_CAST(NULL AS STRING) AS coupon,
  SAFE_CAST(NULL AS STRING) AS currency,
  SAFE_CAST(NULL AS FLOAT64) AS discount,
  SAFE_CAST(NULL AS STRING) AS event_text,
  SAFE_CAST(NULL AS STRING) AS order_id,
  SAFE_CAST(NULL AS STRING) AS payment_type,
  SAFE_CAST(NULL AS STRING) AS products,
  SAFE_CAST(NULL AS FLOAT64) AS revenue,
  SAFE_CAST(NULL AS FLOAT64) AS shipping,
  SAFE_CAST(NULL AS STRING) AS status,
  SAFE_CAST(NULL AS FLOAT64) AS subtotal,
  SAFE_CAST(NULL AS FLOAT64) AS tax,
  SAFE_CAST(NULL AS FLOAT64) AS total,
  SAFE_CAST(NULL AS STRING) AS type,
  SAFE_CAST(NULL AS FLOAT64) AS value,
  SAFE_CAST(NULL AS STRING) AS anonymous_id,
  SAFE_CAST(NULL AS STRING) AS user_id,
  SAFE_CAST(NULL AS TIMESTAMP) AS original_timestamp,
  -- Context fields that would come from get_shared_event_attributes
  SAFE_CAST(NULL AS STRING) AS context_anonymous_id,
  SAFE_CAST(NULL AS STRING) AS context_campaign_content,
  SAFE_CAST(NULL AS STRING) AS context_campaign_id,
  SAFE_CAST(NULL AS STRING) AS context_campaign_klaviyo_id,
  SAFE_CAST(NULL AS STRING) AS context_campaign_medium,
  SAFE_CAST(NULL AS STRING) AS context_campaign_name,
  SAFE_CAST(NULL AS STRING) AS context_campaign_source,
  SAFE_CAST(NULL AS STRING) AS context_campaign_term,
  SAFE_CAST(NULL AS STRING) AS context_country_code,
  SAFE_CAST(NULL AS STRING) AS context_fb_external_id,
  SAFE_CAST(NULL AS STRING) AS context_fb_fbc,
  SAFE_CAST(NULL AS STRING) AS context_fb_fbp,
  SAFE_CAST(NULL AS STRING) AS context_fueled_external_id,
  SAFE_CAST(NULL AS STRING) AS context_ga_4_client_id,
  SAFE_CAST(NULL AS STRING) AS context_ga_4_session_id,
  SAFE_CAST(NULL AS STRING) AS context_ga_4_user_id,
  SAFE_CAST(NULL AS STRING) AS context_ip,
  SAFE_CAST(NULL AS STRING) AS context_klaviyo_exchange_id,
  SAFE_CAST(NULL AS STRING) AS context_locale,
  SAFE_CAST(NULL AS STRING) AS context_os_name,
  SAFE_CAST(NULL AS STRING) AS context_referrer,
  SAFE_CAST(NULL AS STRING) AS context_source_id,
  SAFE_CAST(NULL AS STRING) AS context_source_type,
  SAFE_CAST(NULL AS BOOL) AS context_tracking_consent,
  SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_analytics,
  SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_marketing,
  SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_preferences,
  SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_sale_of_data,
  SAFE_CAST(NULL AS STRING) AS context_timezone,
  SAFE_CAST(NULL AS STRING) AS context_url,
  SAFE_CAST(NULL AS STRING) AS context_user_agent,
  SAFE_CAST(NULL AS STRING) AS context_user_id,
  SAFE_CAST(NULL AS STRING) AS context_version,
  SAFE_CAST(NULL AS STRING) AS context_library_version,
  SAFE_CAST(NULL AS STRING) AS context_library_name,
  SAFE_CAST(NULL AS STRING) AS context_endpoint_version,
  SAFE_CAST(NULL AS STRING) AS context_passed_ip,
  SAFE_CAST(NULL AS STRING) AS context_source,
  SAFE_CAST(NULL AS BOOL) AS context_debug,
  SAFE_CAST(NULL AS STRING) AS context_app,
  SAFE_CAST(NULL AS STRING) AS context_request_ip,
  SAFE_CAST(NULL AS STRING) AS context_session_id,
  SAFE_CAST(NULL AS STRING) AS context_destination_type,
  SAFE_CAST(NULL AS STRING) AS context_destination_id,
  SAFE_CAST(NULL AS STRING) AS context_rudderstack_source,
  SAFE_CAST(NULL AS BOOL) AS context_offline,
  SAFE_CAST(NULL AS BOOL) AS context_initialized,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_functional,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_data_sharing,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_analytics,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_advertising,
  -- event_id as the last column
  SAFE_CAST(NULL AS STRING) AS event_id
FROM (SELECT 1) as dummy
WHERE FALSE

{% endif %}