{{ config(materialized='ephemeral') }}

{% if var('include_s3_destination_data', false) %}

SELECT
    JSON_VALUE(context, '$.fb.eventId')                                                AS context_fb_event_id,
    SAFE_CAST(NULL AS STRING)                                                               AS context_rudderstack_source,
    JSON_VALUE(context, '$.ip')                                                        AS context_ip,
    event_name                                                                         AS event,
    JSON_VALUE(context, '$.locale')                                                    AS context_locale,
    JSON_VALUE(properties, '$.url')                                                    AS url,
    JSON_VALUE(properties, '$.list')                                                   AS list,
    SAFE_CAST(JSON_VALUE(properties, '$.width') AS INT64)                                   AS context_page_width,
    JSON_VALUE(context, '$.campaign.gclid')                                            AS context_campaign_gclid,
    event_name                                                                         AS event_text,
    userId                                                                             AS user_id,
    TIMESTAMP_SECONDS(hydration_timestamp)                                             AS received_at,
    JSON_VALUE(context, '$.klaviyoExchangeId')                                         AS context_klaviyo_exchange_id,
    sourceEndpointId                                                                   AS context_source_id,
    JSON_VALUE(properties, '$.sku')                                                    AS sku,
    JSON_VALUE(context, '$.campaign.name')                                             AS context_campaign_name,
    JSON_VALUE(context, '$.library.name')                                              AS context_library_name,
    JSON_VALUE(context, '$.traits.address.countryCode')                                AS context_traits_address_country_code,
    JSON_VALUE(context, '$.fb.fbc')                                                    AS context_fb_fbc,
    JSON_VALUE(context, '$.version')                                                   AS context_version,
    COALESCE(anonymousId, JSON_VALUE(context, '$.anonymousId'))                        AS context_anonymous_id,
    JSON_VALUE(context, '$.page.title')                                                AS context_page_title,
    JSON_VALUE(context, '$.campaign.klaviyo_id')                                       AS context_campaign_klaviyo_id,
    SAFE_CAST(JSON_VALUE(properties, '$.quantity') AS STRING)                                AS quantity,
    SAFE_CAST(JSON_VALUE(properties, '$.height') AS INT64)                                  AS context_page_height,
    JSON_VALUE(properties, '$.category')                                               AS category,
    JSON_VALUE(properties, '$.search')                                                 AS context_page_search,
    SAFE_CAST(NULL AS STRING)                                                               AS context_source_type,
    COALESCE(sessionId, JSON_VALUE(context, '$.sessionId'))                            AS context_session_id,
    JSON_VALUE(context, '$.timezone')                                                  AS context_timezone,
    COALESCE(
        JSON_VALUE(properties, '$.phone'),
        JSON_VALUE(customer,   '$.phone'),
        JSON_VALUE(context,    '$.traits.phone')
    )                                                                                  AS context_traits_phone,
    JSON_VALUE(context, '$.app')                                                       AS context_app,
    TIMESTAMP_SECONDS(original_timestamp)                                              AS loaded_at,
    JSON_VALUE(context, '$.page.path')                                                 AS context_page_path,
    JSON_VALUE(context, '$.ga4.sessionId')                                             AS context_ga4_session_id,
    JSON_VALUE(properties, '$.variant')                                                AS variant,
    schema_version                                                                     AS context_endpoint_version,
    JSON_VALUE(context, '$.campaign.source')                                           AS context_source,
    JSON_VALUE(context, '$.traits.visitorType')                                        AS context_traits_visitor_type,
    JSON_VALUE(properties, '$.merchantCenterProductId')                                AS merchant_center_product_id,
    SAFE_CAST(JSON_VALUE(context, '$.offline') AS BOOL)                                     AS context_offline,
    JSON_VALUE(context, '$.os.name')                                                   AS context_os_name,
    JSON_VALUE(context, '$.page.url')                                                  AS context_page_url,
    SAFE_CAST(NULL AS STRING)                                                               AS context_destination_type,
    JSON_VALUE(context, '$.ga4.userId')                                                AS context_ga4_user_id,
    JSON_VALUE(properties, '$.imageUrl')                                               AS image_url,
    SAFE_CAST(JSON_VALUE(context, '$.campaign.term') AS BOOL)                               AS context_campaign_term,
    SAFE_CAST(JSON_VALUE(context, '$.debug') AS BOOL)                                       AS context_debug,
    JSON_VALUE(context, '$.campaign.content')                                          AS context_campaign_content,
    JSON_VALUE(context, '$.campaign.id')                                               AS context_campaign_id,
    JSON_VALUE(context, '$.userAgent')                                                 AS context_user_agent,
    JSON_VALUE(context, '$.fb.fbp')                                                    AS context_fb_fbp,
    JSON_VALUE(context, '$.ip')                                                        AS context_request_ip,
    JSON_VALUE(properties, '$.product_id')                                             AS product_id,
    JSON_VALUE(context, '$.campaign.medium')                                           AS context_campaign_medium,
    JSON_VALUE(context, '$.library.version')                                           AS context_library_version,
    JSON_VALUE(properties, '$.compare_at_price')                                       AS compare_at_price,
    JSON_VALUE(properties, '$.variantName')                                            AS variant_name,
    JSON_VALUE(context, '$.fb.externalId')                                             AS context_fb_external_id,
    JSON_VALUE(properties, '$.currency')                                               AS currency,
    TIMESTAMP_SECONDS(original_timestamp)                                              AS original_timestamp,
    SAFE_CAST(NULL AS STRING)                                                               AS context_destination_id,
    JSON_VALUE(properties, '$.brand')                                                  AS brand,
    JSON_VALUE(context, '$.campaign.source')                                           AS context_campaign_source,
    JSON_VALUE(properties, '$.variant_id')                                             AS variant_id,
    'server'                                                                           AS channel,
    SAFE_CAST(JSON_VALUE(properties, '$.position') AS INT64)                                AS position,
    SAFE_CAST(JSON_VALUE(properties, '$.price') AS FLOAT64)                                 AS price,
    TIMESTAMP_SECONDS(original_timestamp)                                              AS sent_at,
    COALESCE(
        JSON_VALUE(properties, '$.email'),
        JSON_VALUE(customer,   '$.email'),
        JSON_VALUE(context,    '$.traits.email')
    )                                                                                  AS context_traits_email,
    SAFE_CAST(JSON_VALUE(context, '$.initialized') AS BOOL)                                 AS context_initialized,
    TIMESTAMP_SECONDS(original_timestamp)                                              AS uuid_ts,
    JSON_VALUE(properties, '$.name')                                                   AS name,
    JSON_VALUE(context, '$.page.referrer')                                             AS context_referrer,
    event_id                                                                           AS id,
    TIMESTAMP_SECONDS(original_timestamp)                                              AS timestamp,
    JSON_VALUE(context, '$.page.referrer')                                             AS context_page_referrer,
    JSON_VALUE(properties, '$.image')                                                  AS image,
    JSON_VALUE(context, '$.ga4.clientId')                                              AS context_ga4_client_id,
    JSON_VALUE(context, '$.fueledExternalId')                                          AS context_fueled_external_id,
    TO_JSON_STRING(JSON_VALUE(properties, '$.collections'))                            AS collections,
    JSON_VALUE(context, '$.traits.address.country')                                    AS context_traits_address_country,
    COALESCE(
        JSON_VALUE(context, '$.traits.externalCustomerId'),
        JSON_VALUE(customer,   '$.externalCustomerId')
    )                                                                                  AS context_traits_external_customer_id,
    JSON_VALUE(context, '$.traits.address.street')                                     AS context_traits_address_street,
    COALESCE(
        JSON_VALUE(properties, '$.first_name'),
        JSON_VALUE(customer,   '$.firstName'),
        JSON_VALUE(context,    '$.traits.firstName')
    )                                                                                  AS context_traits_first_name,
    JSON_VALUE(context, '$.traits.address.city')                                       AS context_traits_address_city,
    JSON_VALUE(context, '$.traits.address.stateCode')                                  AS context_traits_address_state_code,
    JSON_VALUE(context, '$.traits.name')                                               AS context_traits_name,
    JSON_VALUE(context, '$.traits.address.state')                                      AS context_traits_address_state,
    JSON_VALUE(context, '$.traits.shopifyCustomerId')                                  AS context_traits_shopify_customer_id,
    JSON_VALUE(context, '$.traits.address.postalCode')                                 AS context_traits_address_postal_code,
    COALESCE(
        JSON_VALUE(properties, '$.last_name'),
        JSON_VALUE(customer,   '$.lastName'),
        JSON_VALUE(context,    '$.traits.lastName')
    )                                                                                  AS context_traits_last_name,
    SAFE_CAST(NULL AS STRING)                                                               AS context_campaign_redirect,
    JSON_VALUE(context, '$.page.hash')                                                 AS context_page_hash,
    SAFE_CAST(NULL AS STRING)                                                               AS context_campaign_source_platform,
    JSON_VALUE(context, '$.campaign.agid')                                             AS context_campaign_agid,
    JSON_VALUE(context, '$.campaign.audience')                                         AS context_campaign_audience,
    SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.analytics') AS BOOL)                   AS context_tracking_consent_analytics,
    SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.saleOfData') AS BOOL)                  AS context_tracking_consent_sale_of_data,
    SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.preferences') AS BOOL)                 AS context_tracking_consent_preferences,
    SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.marketing') AS BOOL)                   AS context_tracking_consent_marketing,
    JSON_VALUE(properties, '$.referrer')                                               AS referrer,
    JSON_VALUE(context, '$.campaign.marketingAudience')                                AS context_campaign_marketing_audience,
    SAFE_CAST(NULL AS STRING)                                                               AS context_campaign_targeting,
    JSON_VALUE(context, '$.ipv6')                                                      AS context_ipv6,
    JSON_VALUE(context, '$.ipv4')                                                      AS context_ipv4,
    SAFE_CAST(NULL AS BOOL)                                                                 AS context_category_preferences_advertising,
    SAFE_CAST(NULL AS BOOL)                                                                 AS context_category_preferences_data_sharing,
    SAFE_CAST(NULL AS BOOL)                                                                 AS context_category_preferences_functional,
    SAFE_CAST(NULL AS BOOL)                                                                 AS context_category_preferences_analytics,
    JSON_VALUE(context, '$.campaign.marketingTactic')                                  AS context_campaign_marketing_tactic,
    SAFE_CAST(NULL AS STRING)                                                               AS context_traits_custom_client_id,
    SAFE_CAST(JSON_VALUE(context, '$.traits.ecommerceEvent') AS BOOL)                       AS context_traits_ecommerce_event,
    SAFE_CAST(NULL AS STRING)                                                               AS context_traits_fired_from,
    JSON_VALUE(context, '$.opensendIdToken')                                           AS context_opensend_id_token,
    JSON_VALUE(context, '$.opensendPersistentId')                                      AS context_opensend_persistent_id,
    JSON_VALUE(properties, '$.cart_id')                                                AS cart_id,
    SAFE_CAST(JSON_VALUE(context, '$.traits.orderCount') AS INT64)                          AS context_traits_order_count

FROM {{ source('s3_destination_fueled_events','fueled_events') }}
WHERE event_name = 'Product Added'

UNION ALL

SELECT
    SAFE_CAST(NULL AS STRING) AS context_fb_event_id,
    SAFE_CAST(NULL AS STRING) AS context_rudderstack_source,
    SAFE_CAST(NULL AS STRING) AS context_ip,
    SAFE_CAST(NULL AS STRING) AS event,
    SAFE_CAST(NULL AS STRING) AS context_locale,
    SAFE_CAST(NULL AS STRING) AS url,
    SAFE_CAST(NULL AS STRING) AS list,
    SAFE_CAST(NULL AS INT64) AS context_page_width,
    SAFE_CAST(NULL AS STRING) AS context_campaign_gclid,
    SAFE_CAST(NULL AS STRING) AS event_text,
    SAFE_CAST(NULL AS STRING) AS user_id,
    SAFE_CAST(NULL AS TIMESTAMP) AS received_at,
    SAFE_CAST(NULL AS STRING) AS context_klaviyo_exchange_id,
    SAFE_CAST(NULL AS STRING) AS context_source_id,
    SAFE_CAST(NULL AS STRING) AS sku,
    SAFE_CAST(NULL AS STRING) AS context_campaign_name,
    SAFE_CAST(NULL AS STRING) AS context_library_name,
    SAFE_CAST(NULL AS STRING) AS context_traits_address_country_code,
    SAFE_CAST(NULL AS STRING) AS context_fb_fbc,
    SAFE_CAST(NULL AS STRING) AS context_version,
    SAFE_CAST(NULL AS STRING) AS context_anonymous_id,
    SAFE_CAST(NULL AS STRING) AS context_page_title,
    SAFE_CAST(NULL AS STRING) AS context_campaign_klaviyo_id,
    SAFE_CAST(NULL AS STRING) AS quantity,
    SAFE_CAST(NULL AS INT64) AS context_page_height,
    SAFE_CAST(NULL AS STRING) AS category,
    SAFE_CAST(NULL AS STRING) AS context_page_search,
    SAFE_CAST(NULL AS STRING) AS context_source_type,
    SAFE_CAST(NULL AS STRING) AS context_session_id,
    SAFE_CAST(NULL AS STRING) AS context_timezone,
    SAFE_CAST(NULL AS STRING) AS context_traits_phone,
    SAFE_CAST(NULL AS STRING) AS context_app,
    SAFE_CAST(NULL AS TIMESTAMP) AS loaded_at,
    SAFE_CAST(NULL AS STRING) AS context_page_path,
    SAFE_CAST(NULL AS STRING) AS context_ga4_session_id,
    SAFE_CAST(NULL AS STRING) AS variant,
    SAFE_CAST(NULL AS STRING) AS context_endpoint_version,
    SAFE_CAST(NULL AS STRING) AS context_source,
    SAFE_CAST(NULL AS STRING) AS context_traits_visitor_type,
    SAFE_CAST(NULL AS STRING) AS merchant_center_product_id,
    SAFE_CAST(NULL AS BOOL) AS context_offline,
    SAFE_CAST(NULL AS STRING) AS context_os_name,
    SAFE_CAST(NULL AS STRING) AS context_page_url,
    SAFE_CAST(NULL AS STRING) AS context_destination_type,
    SAFE_CAST(NULL AS STRING) AS context_ga4_user_id,
    SAFE_CAST(NULL AS STRING) AS image_url,
    SAFE_CAST(NULL AS BOOL) AS context_campaign_term,
    SAFE_CAST(NULL AS BOOL) AS context_debug,
    SAFE_CAST(NULL AS STRING) AS context_campaign_content,
    SAFE_CAST(NULL AS STRING) AS context_campaign_id,
    SAFE_CAST(NULL AS STRING) AS context_user_agent,
    SAFE_CAST(NULL AS STRING) AS context_fb_fbp,
    SAFE_CAST(NULL AS STRING) AS context_request_ip,
    SAFE_CAST(NULL AS STRING) AS product_id,
    SAFE_CAST(NULL AS STRING) AS context_campaign_medium,
    SAFE_CAST(NULL AS STRING) AS context_library_version,
    SAFE_CAST(NULL AS STRING) AS compare_at_price,
    SAFE_CAST(NULL AS STRING) AS variant_name,
    SAFE_CAST(NULL AS STRING) AS context_fb_external_id,
    SAFE_CAST(NULL AS STRING) AS currency,
    SAFE_CAST(NULL AS TIMESTAMP) AS original_timestamp,
    SAFE_CAST(NULL AS STRING) AS context_destination_id,
    SAFE_CAST(NULL AS STRING) AS brand,
    SAFE_CAST(NULL AS STRING) AS context_campaign_source,
    SAFE_CAST(NULL AS STRING) AS variant_id,
    SAFE_CAST(NULL AS STRING) AS channel,
    SAFE_CAST(NULL AS INT64) AS position,
    SAFE_CAST(NULL AS FLOAT64) AS price,
    SAFE_CAST(NULL AS TIMESTAMP) AS sent_at,
    SAFE_CAST(NULL AS STRING) AS context_traits_email,
    SAFE_CAST(NULL AS BOOL) AS context_initialized,
    SAFE_CAST(NULL AS TIMESTAMP) AS uuid_ts,
    SAFE_CAST(NULL AS STRING) AS name,
    SAFE_CAST(NULL AS STRING) AS context_referrer,
    SAFE_CAST(NULL AS STRING) AS id,
    SAFE_CAST(NULL AS TIMESTAMP) AS timestamp,
    SAFE_CAST(NULL AS STRING) AS context_page_referrer,
    SAFE_CAST(NULL AS STRING) AS image,
    SAFE_CAST(NULL AS STRING) AS context_ga4_client_id,
    SAFE_CAST(NULL AS STRING) AS context_fueled_external_id,
    SAFE_CAST(NULL AS STRING) AS collections,
    SAFE_CAST(NULL AS STRING) AS context_traits_address_country,
    SAFE_CAST(NULL AS STRING) AS context_traits_external_customer_id,
    SAFE_CAST(NULL AS STRING) AS context_traits_address_street,
    SAFE_CAST(NULL AS STRING) AS context_traits_first_name,
    SAFE_CAST(NULL AS STRING) AS context_traits_address_city,
    SAFE_CAST(NULL AS STRING) AS context_traits_address_state_code,
    SAFE_CAST(NULL AS STRING) AS context_traits_name,
    SAFE_CAST(NULL AS STRING) AS context_traits_address_state,
    SAFE_CAST(NULL AS STRING) AS context_traits_shopify_customer_id,
    SAFE_CAST(NULL AS STRING) AS context_traits_address_postal_code,
    SAFE_CAST(NULL AS STRING) AS context_traits_last_name,
    SAFE_CAST(NULL AS STRING) AS context_campaign_redirect,
    SAFE_CAST(NULL AS STRING) AS context_page_hash,
    SAFE_CAST(NULL AS STRING) AS context_campaign_source_platform,
    SAFE_CAST(NULL AS STRING) AS context_campaign_agid,
    SAFE_CAST(NULL AS STRING) AS context_campaign_audience,
    SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_analytics,
    SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_sale_of_data,
    SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_preferences,
    SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_marketing,
    SAFE_CAST(NULL AS STRING) AS referrer,
    SAFE_CAST(NULL AS STRING) AS context_campaign_marketing_audience,
    SAFE_CAST(NULL AS STRING) AS context_campaign_targeting,
    SAFE_CAST(NULL AS STRING) AS context_ipv6,
    SAFE_CAST(NULL AS STRING) AS context_ipv4,
    SAFE_CAST(NULL AS BOOL) AS context_category_preferences_advertising,
    SAFE_CAST(NULL AS BOOL) AS context_category_preferences_data_sharing,
    SAFE_CAST(NULL AS BOOL) AS context_category_preferences_functional,
    SAFE_CAST(NULL AS BOOL) AS context_category_preferences_analytics,
    SAFE_CAST(NULL AS STRING) AS context_campaign_marketing_tactic,
    SAFE_CAST(NULL AS STRING) AS context_traits_custom_client_id,
    SAFE_CAST(NULL AS BOOL) AS context_traits_ecommerce_event,
    SAFE_CAST(NULL AS STRING) AS context_traits_fired_from,
    SAFE_CAST(NULL AS STRING) AS context_opensend_id_token,
    SAFE_CAST(NULL AS STRING) AS context_opensend_persistent_id,
    SAFE_CAST(NULL AS STRING) AS cart_id,
    SAFE_CAST(NULL AS INT64) AS context_traits_order_count

{% endif %}
