{{ config(
    materialized='ephemeral'
) }}

{% if var('include_s3_destination_data', false) %}

SELECT
  -- Map each column, use COALESCE or JSON_VALUE as needed
  TIMESTAMP_SECONDS(original_timestamp) AS original_timestamp,
  COALESCE(
      JSON_VALUE(properties, '$.billingAddress.countryCode'),
      JSON_VALUE(context, '$.traits.address.countryCode')
  ) AS billing_address_country_code,
  COALESCE(userId, JSON_VALUE(context, '$.userId')) AS user_id,
  JSON_VALUE(context, '$.userAgent') AS context_user_agent,
  JSON_VALUE(properties, '$.id') AS order_id,
  SAFE_CAST(JSON_VALUE(properties, '$.total') AS FLOAT64) AS value,
  TO_JSON_STRING(JSON_QUERY_ARRAY(properties, '$.products')) AS products,
  JSON_VALUE(context, '$.ip') AS context_passed_ip,
  JSON_VALUE(context, '$.fueledExternalId') AS context_fueled_external_id,
  SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.analytics') AS BOOL) AS context_tracking_consent,
  COALESCE(
      JSON_VALUE(properties, '$.billingAddress.firstName'),
      JSON_VALUE(customer, '$.firstName')
  ) AS billing_address_first_name,
  JSON_VALUE(properties, '$.payment_type') AS payment_type,
  COALESCE(
      JSON_VALUE(properties, '$.billingAddress.lastName'),
      JSON_VALUE(customer, '$.lastName')
  ) AS billing_address_last_name,
  JSON_VALUE(properties, '$.cartId') AS cart_id,
  SAFE_CAST(NULL AS TIMESTAMP) AS loaded_at,
  SAFE_CAST(NULL AS TIMESTAMP) AS received_at,
  JSON_VALUE(properties, '$.billingAddress.postalCode') AS billing_address_postal_code,
  TIMESTAMP_SECONDS(hydration_timestamp) AS timestamp,
  SAFE_CAST(NULL AS TIMESTAMP) AS sent_at,
  JSON_VALUE(properties, '$.currency') AS currency,
  JSON_VALUE(context, '$.fb.externalId') AS context_fb_external_id,
  SAFE_CAST(NULL AS STRING) AS context_source,
  JSON_VALUE(context, '$.url') AS context_url,
  SAFE_CAST(JSON_VALUE(properties, '$.total') AS FLOAT64) AS total,
  JSON_VALUE(context, '$.anonymousId') AS context_anonymous_id,
  SAFE_CAST(JSON_VALUE(properties, '$.total') AS INT64) AS revenue,
  SAFE_CAST(NULL AS STRING) AS context_endpoint_version,
  SAFE_CAST(NULL AS STRING) AS context_source_type,
  JSON_VALUE(context, '$.library.version') AS context_library_version,
  JSON_VALUE(context, '$.ip') AS context_request_ip,
  JSON_VALUE(properties, '$.id') AS id,
  JSON_VALUE(context, '$.fb.fbp') AS context_fb_fbp,
  JSON_VALUE(properties, '$.type') AS type,
  SAFE_CAST('server' AS STRING) AS channel,
  JSON_VALUE(properties, '$.billingAddress.address') AS billing_address_address,
  SAFE_CAST(NULL AS STRING) AS context_destination_type,
  SAFE_CAST(NULL AS STRING) AS context_rudderstack_source,
  JSON_VALUE(context, '$.fb.fbc') AS context_fb_fbc,
  SAFE_CAST(JSON_VALUE(properties, '$.tax') AS INT64) AS tax,
  JSON_VALUE(properties, '$.coupon') AS coupon,
  SAFE_CAST(JSON_VALUE(properties, '$.subtotal') AS INT64) AS subtotal,
  JSON_VALUE(context, '$.ip') AS context_ip,
  SAFE_CAST(NULL AS STRING) AS context_source_id,
  SAFE_CAST(NULL AS STRING) AS affiliation,
  TIMESTAMP_SECONDS(hydration_timestamp) AS uuid_ts,
  JSON_VALUE(properties, '$.billingAddress.country') AS billing_address_country,
  JSON_VALUE(properties, '$.billingAddress.city') AS billing_address_city,
  JSON_VALUE(properties, '$.status') AS status,
  SAFE_CAST('Order Cancelled' AS STRING) AS event,
  JSON_VALUE(properties, '$.billingAddress.phone') AS billing_address_phone,
  SAFE_CAST(NULL AS STRING) AS context_destination_id,
  SAFE_CAST(NULL AS STRING) AS event_text,
  JSON_VALUE(context, '$.library.name') AS context_library_name,
  JSON_VALUE(context, '$.ga4.sessionId') AS context_ga_4_session_id,
  SAFE_CAST(JSON_VALUE(properties, '$.shipping') AS FLOAT64) AS shipping,
  JSON_VALUE(context, '$.ga4.clientId') AS context_ga_4_client_id,
  JSON_VALUE(context, '$.locale') AS context_locale,
  SAFE_CAST(JSON_VALUE(properties, '$.discount') AS INT64) AS discount,
  JSON_VALUE(context, '$.ga4.sessionId') AS context_ga4_session_id,
  JSON_VALUE(context, '$.ga4.clientId') AS context_ga4_client_id,
  JSON_VALUE(properties, '$.billingAddress.state') AS billing_address_state,
  JSON_VALUE(properties, '$.billingAddress.stateCode') AS billing_address_state_code,
  JSON_VALUE(context, '$.userId') AS context_user_id,
  JSON_VALUE(context, '$.klaviyoExchangeId') AS context_klaviyo_exchange_id,
  JSON_VALUE(context, '$.ga4.userId') AS context_ga4_user_id,
  SAFE_CAST(NULL AS STRING) AS billing_address_company,
  JSON_VALUE(context, '$.countryCode') AS context_country_code,
  SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.analytics') AS BOOL) AS context_category_preferences_analytics,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_advertising,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_functional,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_data_sharing
FROM {{ source("s3_destination_fueled_events", "fueled_events") }}
WHERE event_name = 'Order Cancelled'

{% else %}

SELECT
  SAFE_CAST(NULL AS TIMESTAMP) AS original_timestamp,
  SAFE_CAST(NULL AS STRING) AS billing_address_country_code,
  SAFE_CAST(NULL AS STRING) AS user_id,
  SAFE_CAST(NULL AS STRING) AS context_user_agent,
  SAFE_CAST(NULL AS STRING) AS order_id,
  SAFE_CAST(NULL AS FLOAT64) AS value,
  SAFE_CAST(NULL AS STRING) AS products,
  SAFE_CAST(NULL AS STRING) AS context_passed_ip,
  SAFE_CAST(NULL AS STRING) AS context_fueled_external_id,
  SAFE_CAST(NULL AS BOOL) AS context_tracking_consent,
  SAFE_CAST(NULL AS STRING) AS billing_address_first_name,
  SAFE_CAST(NULL AS STRING) AS payment_type,
  SAFE_CAST(NULL AS STRING) AS billing_address_last_name,
  SAFE_CAST(NULL AS STRING) AS cart_id,
  SAFE_CAST(NULL AS TIMESTAMP) AS loaded_at,
  SAFE_CAST(NULL AS TIMESTAMP) AS received_at,
  SAFE_CAST(NULL AS STRING) AS billing_address_postal_code,
  SAFE_CAST(NULL AS TIMESTAMP) AS timestamp,
  SAFE_CAST(NULL AS TIMESTAMP) AS sent_at,
  SAFE_CAST(NULL AS STRING) AS currency,
  SAFE_CAST(NULL AS STRING) AS context_fb_external_id,
  SAFE_CAST(NULL AS STRING) AS context_source,
  SAFE_CAST(NULL AS STRING) AS context_url,
  SAFE_CAST(NULL AS FLOAT64) AS total,
  SAFE_CAST(NULL AS STRING) AS context_anonymous_id,
  SAFE_CAST(NULL AS INT64) AS revenue,
  SAFE_CAST(NULL AS STRING) AS context_endpoint_version,
  SAFE_CAST(NULL AS STRING) AS context_source_type,
  SAFE_CAST(NULL AS STRING) AS context_library_version,
  SAFE_CAST(NULL AS STRING) AS context_request_ip,
  SAFE_CAST(NULL AS STRING) AS id,
  SAFE_CAST(NULL AS STRING) AS context_fb_fbp,
  SAFE_CAST(NULL AS STRING) AS type,
  SAFE_CAST(NULL AS STRING) AS channel,
  SAFE_CAST(NULL AS STRING) AS billing_address_address,
  SAFE_CAST(NULL AS STRING) AS context_destination_type,
  SAFE_CAST(NULL AS STRING) AS context_rudderstack_source,
  SAFE_CAST(NULL AS STRING) AS context_fb_fbc,
  SAFE_CAST(NULL AS INT64) AS tax,
  SAFE_CAST(NULL AS STRING) AS coupon,
  SAFE_CAST(NULL AS INT64) AS subtotal,
  SAFE_CAST(NULL AS STRING) AS context_ip,
  SAFE_CAST(NULL AS STRING) AS context_source_id,
  SAFE_CAST(NULL AS STRING) AS affiliation,
  SAFE_CAST(NULL AS TIMESTAMP) AS uuid_ts,
  SAFE_CAST(NULL AS STRING) AS billing_address_country,
  SAFE_CAST(NULL AS STRING) AS billing_address_city,
  SAFE_CAST(NULL AS STRING) AS status,
  SAFE_CAST(NULL AS STRING) AS event,
  SAFE_CAST(NULL AS STRING) AS billing_address_phone,
  SAFE_CAST(NULL AS STRING) AS context_destination_id,
  SAFE_CAST(NULL AS STRING) AS event_text,
  SAFE_CAST(NULL AS STRING) AS context_library_name,
  SAFE_CAST(NULL AS STRING) AS context_ga_4_session_id,
  SAFE_CAST(NULL AS FLOAT64) AS shipping,
  SAFE_CAST(NULL AS STRING) AS context_ga_4_client_id,
  SAFE_CAST(NULL AS STRING) AS context_locale,
  SAFE_CAST(NULL AS INT64) AS discount,
  SAFE_CAST(NULL AS STRING) AS context_ga4_session_id,
  SAFE_CAST(NULL AS STRING) AS context_ga4_client_id,
  SAFE_CAST(NULL AS STRING) AS billing_address_state,
  SAFE_CAST(NULL AS STRING) AS billing_address_state_code,
  SAFE_CAST(NULL AS STRING) AS context_user_id,
  SAFE_CAST(NULL AS STRING) AS context_klaviyo_exchange_id,
  SAFE_CAST(NULL AS STRING) AS context_ga4_user_id,
  SAFE_CAST(NULL AS STRING) AS billing_address_company,
  SAFE_CAST(NULL AS STRING) AS context_country_code,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_analytics,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_advertising,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_functional,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_data_sharing
FROM (SELECT 1) as dummy
WHERE FALSE

{% endif %}
