{{ config(
    materialized='ephemeral'
) }}

{% if var('include_s3_destination_data', false) %}
SELECT
  JSON_VALUE(context, '$.traits.address.street') AS context_traits_address_street,
  SAFE_CAST(NULL AS STRING) AS address_country_code,
  JSON_VALUE(context, '$.traits.externalCustomerId') AS context_traits_external_customer_id,
  JSON_VALUE(context, '$.version') AS context_version,
  JSON_VALUE(context, '$.ga4.clientId') AS context_ga4_client_id,
  SAFE_CAST(NULL AS STRING) AS context_ip,
  JSON_VALUE(context, '$.ip') AS context_request_ip,
  JSON_VALUE(context, '$.userAgent') AS context_user_agent,
  COALESCE(JSON_VALUE(properties, '$.first_name'), JSON_VALUE(customer, '$.firstName'), JSON_VALUE(context, '$.traits.firstName')) AS first_name,
  SAFE_CAST(JSON_VALUE(context, '$.debug') AS BOOL) as context_debug,
  sourceEndpointId AS context_source_id,
  TIMESTAMP_SECONDS(hydration_timestamp) AS loaded_at,
  JSON_VALUE(context, '$.traits.lastName') AS context_traits_last_name,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_country,
  SAFE_CAST(NULL AS STRING) AS context_session_id,
  JSON_VALUE(context, '$.campaign.medium') AS context_campaign_medium,
  JSON_VALUE(context, '$.fb.fbp') AS context_fb_fbp,
  JSON_VALUE(context, '$.page.url') AS context_page_url,
  JSON_VALUE(context, '$.fb.eventId') AS context_fb_event_id,
  SAFE_CAST(NULL AS STRING) AS visitor_type,
  SAFE_CAST(NULL AS STRING) AS channel,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_country_code,
  SAFE_CAST(NULL AS STRING) AS address_city,
  SAFE_CAST(NULL AS STRING) AS context_source_type,
  TIMESTAMP_SECONDS(hydration_timestamp) AS received_at,
  JSON_VALUE(context, '$.campaign.term') AS context_campaign_term,
  JSON_VALUE(context, '$.timezone') AS context_timezone,
  JSON_VALUE(context, '$.campaign.source') AS context_campaign_source,
  event_id AS id,
  JSON_VALUE(context, '$.page.title') AS context_page_title,
  COALESCE(anonymousId, JSON_VALUE(context, '$.anonymousId')) AS context_anonymous_id,
  SAFE_CAST(JSON_VALUE(context, '$.page.height') AS INT64) as context_page_height,
  TIMESTAMP_SECONDS(original_timestamp) AS uuid_ts,
  JSON_VALUE(context, '$.campaign.content') AS context_campaign_content,
  JSON_VALUE(context, '$.locale') AS context_locale,
  COALESCE(JSON_VALUE(properties, '$.phone'), JSON_VALUE(customer, '$.phone'), JSON_VALUE(context, '$.traits.phone')) AS phone,
  SAFE_CAST(NULL AS STRING) AS address_state_code,
  SAFE_CAST(NULL AS STRING) AS address_postal_code,
  JSON_VALUE(context, '$.traits.phone') AS context_traits_phone,
  JSON_VALUE(context, '$.library.version') AS context_library_version,
  SAFE_CAST(JSON_VALUE(context, '$.initialized') AS BOOL) as context_initialized,
  SAFE_CAST(NULL AS STRING) AS context_destination_id,
  TIMESTAMP_SECONDS(original_timestamp) AS timestamp,
  event_name AS event_text,
  JSON_VALUE(context, '$.traits.firstName') AS context_traits_first_name,
  SAFE_CAST(JSON_VALUE(context, '$.traits.orderCount') AS INT64) as context_traits_order_count,
  SAFE_CAST(NULL AS STRING) AS address_country,
  JSON_VALUE(context, '$.campaign.id') AS context_campaign_id,
  SAFE_CAST(JSON_VALUE(context, '$.offline') AS BOOL) as context_offline,
  JSON_VALUE(context, '$.page.search') AS context_page_search,
  SAFE_CAST(NULL AS STRING) AS context_referrer,
  SAFE_CAST(NULL AS STRING) AS context_campaign_gclid,
  COALESCE(JSON_VALUE(properties, '$.email'), JSON_VALUE(customer, '$.email'), JSON_VALUE(context, '$.traits.email')) AS email,
  JSON_VALUE(context, '$.library.name') AS context_library_name,
  event_name AS event,
  JSON_VALUE(context, '$.traits.email') AS context_traits_email,
  JSON_VALUE(context, '$.traits.visitorType') AS context_traits_visitor_type,
  TIMESTAMP_SECONDS(original_timestamp) AS original_timestamp,
  SAFE_CAST(NULL AS STRING) AS context_fb_fbc,
  JSON_VALUE(context, '$.page.referrer') AS context_page_referrer,
  SAFE_CAST(NULL AS STRING) AS context_destination_type,
  JSON_VALUE(context, '$.page.path') AS context_page_path,
  userId AS user_id,
  JSON_VALUE(context, '$.traits.name') AS context_traits_name,
  SAFE_CAST(NULL AS STRING) AS order_count,
  TIMESTAMP_SECONDS(original_timestamp) AS sent_at,
  SAFE_CAST(JSON_VALUE(context, '$.page.width') AS INT64) as context_page_width,
  JSON_VALUE(context, '$.os.name') AS context_os_name,
  JSON_VALUE(context, '$.fueledExternalId') AS context_fueled_external_id,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_state_code,
  SAFE_CAST(NULL AS STRING) AS external_customer_id,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_postal_code,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_state,
  source AS context_rudderstack_source,
  COALESCE(JSON_VALUE(properties, '$.last_name'), JSON_VALUE(customer, '$.lastName'), JSON_VALUE(context, '$.traits.lastName')) AS last_name,
  JSON_VALUE(context, '$.traits.shopifyCustomerId') AS context_traits_shopify_customer_id,
  SAFE_CAST(NULL AS STRING) AS address_street,
  SAFE_CAST(NULL AS STRING) AS name,
  source AS context_source,
  JSON_VALUE(context, '$.ga4.sessionId') AS context_ga4_session_id,
  JSON_VALUE(context, '$.app') AS context_app,
  JSON_VALUE(context, '$.ga4.userId') AS context_ga4_user_id,
  SAFE_CAST(NULL AS STRING) AS address_state,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_city,
  JSON_VALUE(context, '$.campaign.name') AS context_campaign_name,
  JSON_VALUE(context, '$.fb.externalId') AS context_fb_external_id,
  schema_version AS context_endpoint_version,
  JSON_VALUE(context, '$.klaviyoExchangeId') AS context_klaviyo_exchange_id,
  JSON_VALUE(context, '$.campaign.klaviyoId') AS context_campaign_klaviyo_id,
  SAFE_CAST(NULL AS STRING) AS lifetime_value,
  SAFE_CAST(JSON_VALUE(context, '$.traits.lifetimeValue') AS FLOAT64) as context_traits_lifetime_value,
  SAFE_CAST(NULL AS STRING) AS context_page_hash,
  JSON_VALUE(context, '$.campaign.redirect') AS context_campaign_redirect,
  SAFE_CAST(NULL AS STRING) AS context_campaign_source_platform,
  JSON_VALUE(context, '$.campaign.audience') AS context_campaign_audience,
  SAFE_CAST(JSON_VALUE(context, '$.campaign.agid') AS BOOL) AS context_campaign_agid,
  JSON_VALUE(context, '$.ipv6') AS context_ipv6,
  JSON_VALUE(context, '$.ipv4') AS context_ipv4,
  SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.preferences') AS BOOL) as context_tracking_consent_preferences,
  SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.analytics') AS BOOL) as context_tracking_consent_analytics,
  SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.marketing') AS BOOL) as context_tracking_consent_marketing,
  SAFE_CAST(JSON_VALUE(context, '$.trackingConsent.saleOfData') AS BOOL) as context_tracking_consent_sale_of_data,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_analytics,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_advertising,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_data_sharing,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_functional,
  SAFE_CAST(NULL AS STRING) AS context_campaign_fbaudience
FROM {{ source("s3_destination_fueled_events", "fueled_events") }}
WHERE event_name = 'Newsletter Signup Completed'

{% else %}

SELECT
  SAFE_CAST(NULL AS STRING) AS context_traits_address_street,
  SAFE_CAST(NULL AS STRING) AS address_country_code,
  SAFE_CAST(NULL AS STRING) AS context_traits_external_customer_id,
  SAFE_CAST(NULL AS STRING) AS context_version,
  SAFE_CAST(NULL AS STRING) AS context_ga4_client_id,
  SAFE_CAST(NULL AS STRING) AS context_ip,
  SAFE_CAST(NULL AS STRING) AS context_request_ip,
  SAFE_CAST(NULL AS STRING) AS context_user_agent,
  SAFE_CAST(NULL AS STRING) AS first_name,
  SAFE_CAST(NULL AS BOOL) AS context_debug,
  SAFE_CAST(NULL AS STRING) AS context_source_id,
  SAFE_CAST(NULL AS TIMESTAMP) AS loaded_at,
  SAFE_CAST(NULL AS STRING) AS context_traits_last_name,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_country,
  SAFE_CAST(NULL AS STRING) AS context_session_id,
  SAFE_CAST(NULL AS STRING) AS context_campaign_medium,
  SAFE_CAST(NULL AS STRING) AS context_fb_fbp,
  SAFE_CAST(NULL AS STRING) AS context_page_url,
  SAFE_CAST(NULL AS STRING) AS context_fb_event_id,
  SAFE_CAST(NULL AS STRING) AS visitor_type,
  SAFE_CAST(NULL AS STRING) AS channel,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_country_code,
  SAFE_CAST(NULL AS STRING) AS address_city,
  SAFE_CAST(NULL AS STRING) AS context_source_type,
  SAFE_CAST(NULL AS TIMESTAMP) AS received_at,
  SAFE_CAST(NULL AS STRING) AS context_campaign_term,
  SAFE_CAST(NULL AS STRING) AS context_timezone,
  SAFE_CAST(NULL AS STRING) AS context_campaign_source,
  SAFE_CAST(NULL AS STRING) AS id,
  SAFE_CAST(NULL AS STRING) AS context_page_title,
  SAFE_CAST(NULL AS STRING) AS context_anonymous_id,
  SAFE_CAST(NULL AS INT64) AS context_page_height,
  SAFE_CAST(NULL AS TIMESTAMP) AS uuid_ts,
  SAFE_CAST(NULL AS STRING) AS context_campaign_content,
  SAFE_CAST(NULL AS STRING) AS context_locale,
  SAFE_CAST(NULL AS STRING) AS phone,
  SAFE_CAST(NULL AS STRING) AS address_state_code,
  SAFE_CAST(NULL AS STRING) AS address_postal_code,
  SAFE_CAST(NULL AS STRING) AS context_traits_phone,
  SAFE_CAST(NULL AS STRING) AS context_library_version,
  SAFE_CAST(NULL AS BOOL) AS context_initialized,
  SAFE_CAST(NULL AS STRING) AS context_destination_id,
  SAFE_CAST(NULL AS TIMESTAMP) AS timestamp,
  SAFE_CAST(NULL AS STRING) AS event_text,
  SAFE_CAST(NULL AS STRING) AS context_traits_first_name,
  SAFE_CAST(NULL AS INT64) AS context_traits_order_count,
  SAFE_CAST(NULL AS STRING) AS address_country,
  SAFE_CAST(NULL AS STRING) AS context_campaign_id,
  SAFE_CAST(NULL AS BOOL) AS context_offline,
  SAFE_CAST(NULL AS STRING) AS context_page_search,
  SAFE_CAST(NULL AS STRING) AS context_referrer,
  SAFE_CAST(NULL AS STRING) AS context_campaign_gclid,
  SAFE_CAST(NULL AS STRING) AS email,
  SAFE_CAST(NULL AS STRING) AS context_library_name,
  SAFE_CAST(NULL AS STRING) AS event,
  SAFE_CAST(NULL AS STRING) AS context_traits_email,
  SAFE_CAST(NULL AS STRING) AS context_traits_visitor_type,
  SAFE_CAST(NULL AS TIMESTAMP) AS original_timestamp,
  SAFE_CAST(NULL AS STRING) AS context_fb_fbc,
  SAFE_CAST(NULL AS STRING) AS context_page_referrer,
  SAFE_CAST(NULL AS STRING) AS context_destination_type,
  SAFE_CAST(NULL AS STRING) AS context_page_path,
  SAFE_CAST(NULL AS STRING) AS user_id,
  SAFE_CAST(NULL AS STRING) AS context_traits_name,
  SAFE_CAST(NULL AS INT64) AS order_count,
  SAFE_CAST(NULL AS TIMESTAMP) AS sent_at,
  SAFE_CAST(NULL AS INT64) AS context_page_width,
  SAFE_CAST(NULL AS STRING) AS context_os_name,
  SAFE_CAST(NULL AS STRING) AS context_fueled_external_id,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_state_code,
  SAFE_CAST(NULL AS STRING) AS external_customer_id,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_postal_code,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_state,
  SAFE_CAST(NULL AS STRING) AS context_rudderstack_source,
  SAFE_CAST(NULL AS STRING) AS last_name,
  SAFE_CAST(NULL AS STRING) AS context_traits_shopify_customer_id,
  SAFE_CAST(NULL AS STRING) AS address_street,
  SAFE_CAST(NULL AS STRING) AS name,
  SAFE_CAST(NULL AS STRING) AS context_source,
  SAFE_CAST(NULL AS STRING) AS context_ga4_session_id,
  SAFE_CAST(NULL AS STRING) AS context_app,
  SAFE_CAST(NULL AS STRING) AS context_ga4_user_id,
  SAFE_CAST(NULL AS STRING) AS address_state,
  SAFE_CAST(NULL AS STRING) AS context_traits_address_city,
  SAFE_CAST(NULL AS STRING) AS context_campaign_name,
  SAFE_CAST(NULL AS STRING) AS context_fb_external_id,
  SAFE_CAST(NULL AS STRING) AS context_endpoint_version,
  SAFE_CAST(NULL AS STRING) AS context_klaviyo_exchange_id,
  SAFE_CAST(NULL AS STRING) AS context_campaign_klaviyo_id,
  SAFE_CAST(NULL AS FLOAT64) AS lifetime_value,
  SAFE_CAST(NULL AS FLOAT64) AS context_traits_lifetime_value,
  SAFE_CAST(NULL AS STRING) AS context_page_hash,
  SAFE_CAST(NULL AS STRING) AS context_campaign_redirect,
  SAFE_CAST(NULL AS STRING) AS context_campaign_source_platform,
  SAFE_CAST(NULL AS STRING) AS context_campaign_audience,
  SAFE_CAST(NULL AS BOOL) AS context_campaign_agid,
  SAFE_CAST(NULL AS STRING) AS context_ipv6,
  SAFE_CAST(NULL AS STRING) AS context_ipv4,
  SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_preferences,
  SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_analytics,
  SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_marketing,
  SAFE_CAST(NULL AS BOOL) AS context_tracking_consent_sale_of_data,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_analytics,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_advertising,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_data_sharing,
  SAFE_CAST(NULL AS BOOL) AS context_category_preferences_functional,
  SAFE_CAST(NULL AS STRING) AS context_campaign_fbaudience
FROM (SELECT 1) AS dummy
WHERE FALSE

{% endif %}
