with
    source as (select * from {{ source("fueled_events_atomic", "product_added") }}),

    product_added as (

        select
            context_client_id,
            context_source_type,
            name,
            context_rudderstack_source,
            context_destination_type,
            quantity,
            original_timestamp,
            context_library_name,
            product_id,
            event_text,
            context_source_id,
            channel,
            brand,
            image_url,
            sku,
            context_destination_id,
            context_session_id,
            context_ip,
            event,
            price,
            context_request_ip,
            category,
            timestamp,
            loaded_at,
            sent_at,
            variant,
            context_library_version,
            id,
            user_id,
            uuid_ts,
            context_source,
            context_anonymous_id,
            received_at,
            url,
            position,
            context_page_height,
            context_page_path,
            context_os_name,
            context_debug,
            context_app,
            context_locale,
            context_page_url,
            context_referrer,
            context_page_search,
            context_timezone,
            context_initialized,
            context_user_agent,
            context_page_referrer,
            context_offline,
            context_page_width,
            context_page_title,
            context_campaign_gclid,
            context_campaign_content,
            context_campaign_medium,
            context_campaign_name,
            context_campaign_source,
            context_campaign_term,
            context_page_hash,
            context_campaign_profile,
            context_campaign_id

        from source

    )

select *
from product_added
